# Generated by Django 5.0.6 on 2024-06-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_review_created_at_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
