# Generated by Django 5.0.6 on 2024-06-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0007_book_ebook_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='purchased_books',
            field=models.ManyToManyField(blank=True, related_name='purchased_by', to='tutors.book'),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
